#---------------------------------#
#            Rock RMS             #
#---------------------------------#

# version format
version: 1.3.{build}

# increment flag
pull_requests:
  do_not_increment_build_number: true

# branches to build
branches:
  only:
  - master
  - beta
  - alpha
  - pre-alpha-release

# Do not build on tags (GitHub only)
skip_tags: true

# operating system (build VM template)
image: Visual Studio 2022
configuration: Release
platform: Any CPU

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf true

# clone directory and depth
clone_folder: C:\projects\Rock
clone_depth: 1

# scripts that run after cloning repository
install:
- ps: >-
    $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n"

    $fileContent += $env:priv_key.Replace(' ', "`n")

    $fileContent += "`n-----END RSA PRIVATE KEY-----`n"

    Set-Content c:\users\appveyor\.ssh\id_rsa $fileContent

    git clone -q --depth=1 https://github.com/NewSpring/apollos-onesignal.git c:\projects\apollos-onesignal


# directories to preserve between builds
cache:
# - packages -> **\packages.config # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
# - node_modules # local npm modules

# scripts to run before build
# (New-Object Net.WebClient).DownloadFile('https://dist.nuget.org/win-x86-commandline/v3.4.4/nuget.exe', "$nugetDir\NuGet.exe")
before_build:
- ps: >-
    (Get-Content "C:\projects\Rock\RockWeb\web.config").Replace('<compilation debug="true"', '<compilation debug="false"') | Set-Content "C:\projects\Rock\RockWeb\web.config"

# build configuration
build:
  project: Rock.sln
  publish_wap: true
  parallel: true
  verbosity: minimal

build_script:
- cmd: >-
    nuget restore

    rem -- Allow TypeScript to have more memory for building.
    set NODE_OPTIONS=--max-old-space-size=1536

    "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv"
    "C:\projects\Rock\Rock.sln" /build Release

# flag to stop building if an error throws
matrix:
  fast_finish: true

# test
test:
  assemblies:
    only:
      - Rock.Tests.dll

# IIS artifact configuration
artifacts:
- path: RockWeb
  name: NewSpringRockKit

# deployment configuration
deploy:
- provider: Environment
  name: Alpha (alpha-rock.newspring.cc)
  on:
    branch: alpha