//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { ConnectionOpportunityDetailBag } from "@Obsidian/ViewModels/Blocks/Engagement/ConnectionsHub/connectionOpportunityDetailBag";
import { ConnectionStatusBag } from "@Obsidian/ViewModels/Blocks/Engagement/ConnectionsHub/connectionStatusBag";
import { ListItemBag } from "@Obsidian/ViewModels/Utility/listItemBag";
import { PublicAttributeBag } from "@Obsidian/ViewModels/Utility/publicAttributeBag";

/** The additional configuration options for the Connections Hub block. */
export type ConnectionsHubOptionsBag = {
    connectionOpportunities?: ListItemBag[] | null;

    connectionOpportunityDetailsFromFilter?: ConnectionOpportunityDetailBag | null;

    connectionStates?: ListItemBag[] | null;

    connectionStatusBags?: ConnectionStatusBag[] | null;

    connectionStatuses?: ListItemBag[] | null;

    connectionTypeIdKey?: string | null;

    /** Gets or sets the attributes for Connection Request attributes specified at the Connection Type level. */
    connectionTypeRequestAttributes?: Record<string, PublicAttributeBag> | null;

    iconCssClass?: string | null;

    requestSourceItems?: ListItemBag[] | null;

    title?: string | null;
};
