//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { ConnectionState } from "@Obsidian/Enums/Connection/connectionState";
import { DueStatus } from "@Obsidian/Enums/Connection/dueStatus";
import { ActivityEntryBag } from "@Obsidian/ViewModels/Blocks/Engagement/ConnectionsHub/activityEntryBag";
import { AdditionalRequestBag } from "@Obsidian/ViewModels/Blocks/Engagement/ConnectionsHub/additionalRequestBag";
import { PlacementGroupDetailsBag } from "@Obsidian/ViewModels/Blocks/Engagement/ConnectionsHub/placementGroupDetailsBag";
import { RequesterPersonBag } from "@Obsidian/ViewModels/Blocks/Engagement/ConnectionsHub/requesterPersonBag";
import { ListItemBag } from "@Obsidian/ViewModels/Utility/listItemBag";
import { PublicAttributeBag } from "@Obsidian/ViewModels/Utility/publicAttributeBag";

export type ConnectionRequestDetailsBag = {
    actionItems?: ListItemBag[] | null;

    activityEntries?: ActivityEntryBag[] | null;

    additionalRequests?: AdditionalRequestBag[] | null;

    /** The attributes for the selected Connection Request. */
    attributes?: Record<string, PublicAttributeBag> | null;

    /** The attribute values for the selected Connection Request. */
    attributeValues?: Record<string, string> | null;

    /** The selected Campus on the Connection Request */
    campus?: string | null;

    comments?: string | null;

    connectionOpportunityIcon?: string | null;

    connectionOpportunityName?: string | null;

    connectionRequestIdKey?: string | null;

    connectionState: ConnectionState;

    connectionTypeSource?: string | null;

    connectorPerson?: string | null;

    createdDateTime?: string | null;

    dueDate?: string | null;

    dueStatus: DueStatus;

    followUpDate?: string | null;

    placementGroup?: PlacementGroupDetailsBag | null;

    requesterPerson?: RequesterPersonBag | null;
};
