//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { Guid } from "@Obsidian/Types";
import { ConnectionStatusBag } from "@Obsidian/ViewModels/Blocks/Engagement/ConnectionsHub/connectionStatusBag";
import { ConnectorItemBag } from "@Obsidian/ViewModels/Blocks/Engagement/ConnectionsHub/connectorItemBag";
import { PlacementGroupDetailsBag } from "@Obsidian/ViewModels/Blocks/Engagement/ConnectionsHub/placementGroupDetailsBag";
import { ListItemBag } from "@Obsidian/ViewModels/Utility/listItemBag";

export type ConnectionRequestDetailOptionsBag = {
    areCelebrationsEnabled: boolean;

    areGroupPlacementsEnabled: boolean;

    areRemindersEnabled: boolean;

    badgeGuids?: Guid[] | null;

    connectionStates?: ListItemBag[] | null;

    connectionStatuses?: ConnectionStatusBag[] | null;

    connectorItems?: ConnectorItemBag[] | null;

    isFutureFollowUpEnabled: boolean;

    isRequestSecurityEnabled: boolean;

    isSequentialStatusMode: boolean;

    lavaBadgeBar?: string | null;

    lavaHeadingTemplate?: string | null;

    placementGroups?: PlacementGroupDetailsBag[] | null;

    requestSourceItems?: ListItemBag[] | null;
};
